name: build
on:
  push:
    branches:
      - master
      - main
jobs:

  container-snap-gpt:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: build & push snap-gpt image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/snap-gpt
          docker build snap-gpt --tag snap-gpt
          version=$( cat snap-gpt/setup.cfg | grep version | cut -d "=" -f 2 | tr -d " " )
          docker tag snap-gpt $IMAGE_ID:${version}
          docker push $IMAGE_ID:${version}
          docker tag snap-gpt $IMAGE_ID:latest
          docker push $IMAGE_ID:latest

  container-orfeo-toolbox:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: build & push orfeo-toolbox image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/otb
          docker build orfeo-toolbox --tag otb
          version=$( cat orfeo-toolbox/setup.cfg | grep version | cut -d "=" -f 2 | tr -d " " )
          docker tag otb $IMAGE_ID:${version}
          docker push $IMAGE_ID:${version}
          docker tag otb $IMAGE_ID:latest
          docker push $IMAGE_ID:latest  

  container-gdal:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: build & push orfeo-toolbox image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/gdal
          docker build gdal --tag gdal
          version=$( docker run --rm osgeo/gdal gdal-config --version )
          docker tag gdal $IMAGE_ID:${version}
          docker push $IMAGE_ID:${version}
          docker tag gdal $IMAGE_ID:latest
          docker push $IMAGE_ID:latest  